name: "bug 反馈"              
description: "这是一个bug反馈表单"   
title: 
  value: "# bug反馈"     
labels: ["bug",]          
  
assignees:                         
  - xyz349925756
body:                             
  - type: markdown  
    attributes:     
      value: |      
        感谢您百忙之中抽空给我们反馈bug，我们会尽快解决。
  - type: input    
    id: email     
    attributes:     
      label: Email
      description: "提供您的邮箱,我们会尽快联系您。"
      placeholder: abc@xxx.com
    validations:          
      required: true