---
name: Custom File Creation
about: Use this template to create a file in the repository.
title: "[FILE] "
labels: file-creation
assignees: ''

---

## File Name
<!-- Please specify the file name you want to create -->

## File Location
<!-- Please specify the folder path where the file should be created -->

## File Content
<!-- Please provide the content that should be included in the file -->
