name: 报告                  
description: 报告问题模板   
title: "[报告]: "                   
labels: ["bug", "triage"]    
projects:
  -      
assignees:                         
  - xyz349925756
body:                             
  - type: markdown  
    attributes:    
      value: |      
        感谢您在百忙中抽空给我们反馈问题.