name: 'Create a New File'
description: 'Use this template to create a new file in the repository.'
title: 'New File: [FILE NAME]'
labels: ['new-file']
assignees: ''

body:
  - type: markdown
    attributes:
      value: 'Please fill out the details below to create a new file.'

  - type: input
    id: file_path
    attributes:
      label: 'File Path'
      description: 'Enter the path where the new file should be created. For example, "folder/subfolder/"'
      placeholder: 'folder/subfolder/'
    validations:
      required: true

  - type: input
    id: file_name
    attributes:
      label: 'File Name'
      description: 'Enter the name of the new file, including the extension. For example, "example.txt"'
      placeholder: 'example.txt'
    validations:
      required: true

  - type: textarea
    id: file_content
    attributes:
      label: 'File Content'
      description: 'Enter the content that should be included in the new file.'
      placeholder: 'Enter file content here...'
    validations:
      required: false
