name: "Docker Image Request"              
description: "拉取Docker镜像"   
title: "Docker Image Request"
labels: ["pull",]          
assignees:                         
  - xyz349925756
body:                             
  - type: markdown  
    attributes:     
      value: |      
        请填写你需要拉取的镜像名称譬如 'k8s.gcr.io/pause:3.6'。
  - type: input    
    id: Name    
    attributes:     
      label: "请输入镜像名称"
      description: "必需是官网的镜像名称"
      placeholder: "输入image名称"
      value: k8s.gcr.io/pause:3.6
    validations:          
      required: true