name: Build and Push Docker Image
on:
  issues:
    types:
      - opened

steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Login to DockerHub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build and push
    id: docker_build
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: user/dockerimage:v1

  - name: Get the image digest
    run: echo 'IMAGE_DIGEST='${{ steps.docker_build.outputs.digest }} >> $GITHUB_ENV


  - name: Close issue
    run: gh issue close ${{ github.event.issue.number }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}