name: Docker Image Request

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract Docker Image Name
      id: extract
      run: |
        IMAGE_NAME=$(echo ${{ github.event.issue.body }} | grep -oP '(?<=value: ).*')
        echo {{ IMAGE_NAME }}
        echo "::set-output name=image::$IMAGE_NAME"

        
       
        


        
    - name: Pull Docker Image
      run: |
        docker pull ${{ steps.extract.outputs.image }}

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag ${{ steps.extract.outputs.image }} ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract.outputs.image }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract.outputs.image }}

    - name: Comment Docker Hub URL
      uses: actions/github-script@v5
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Docker image is available at: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/${{ steps.extract.outputs.image }}'
          })

    - name: Close Issue
      uses: actions/github-script@v5
      with:
        script: |
          setTimeout(() => {
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })
          }, 300000) # 5 minutes